### ISSUE TITLE
launch_template parameter is nt working properly

### ISSUE THREAD

**Issue by nik786** [umotif-public/terraform-aws-eks-node-group#13]
**What is the current behavior?**
module "eks-node-group" {
  source = "umotif-public/eks-node-group/aws"
  version = "~> 3.0.0"
  cluster_name = data.aws_eks_cluster.cluster.id
  subnet_ids = flatten([ module.vpc.public_subnets, module.vpc.private_subnets ])
  desired_size = 2
  min_size     = 1
  max_size     = 2
  instance_types = ["t2.micro"]
  ec2_ssh_key = "gghh"
  launch_template = {
    launch_template_name = "foo"
    }
  tags = {
    Environment = "spot"
  }

}

error:

Error: Error in function call

  on .terraform/modules/eks-node-group/main.tf line 60, in resource "aws_eks_node_group" "main":
  60:       version = lookup(launch_template.value, "version")
    |----------------
    | launch_template.value is map of string with 1 element

Call to function "lookup" failed: lookup failed to find 'version'.

**What is the expected behavior?**
launch_template name need to pick

**Comment by Ohid25** [comment]
There is no [default value](https://github.com/umotif-public/terraform-aws-eks-node-group/blob/3.1.0/main.tf#L62) set for `version` so you must supply one. Launch template can take up to three attributes - `id`, `name` and `version`, with `version` as a required attribute and the other two, are optional. `launch_template_name` is not one of them.

Here is an [example](https://github.com/umotif-public/terraform-aws-eks-node-group/blob/master/examples/single-node-group-with-launch-template/main.tf#L117) that you can follow.
