### ISSUE TITLE
single-node-group-with-launch-template is failing during deployment

### ISSUE THREAD

**Issue by 80kk** [umotif-public/terraform-aws-eks-node-group#7]
**What is the current behavior?**

Terraform is failing with the following error:
Error: error waiting for EKS Node Group (eks-xxx:eks-cluster-node-group) creation: unable to find additional information about CREATE_FAILED status, check EKS Node Group (eks-xxx:eks-cluster-node-group) health

Node group status is ```Create failed``` however ec2 instance are up and running. Userdata seems to be executed successfully.

**Comment by marcincuber** [comment]
Hi @80kk 

I just ran the exact example you pointed out and I can't see any issues. I am deploying it in Ireland region (eu-west-1). Could there be wrong something with your setup?

I am using
```
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/aws v3.3.0
+ provider registry.terraform.io/hashicorp/random v2.3.0
```

```
...
module.eks-node-group.aws_eks_node_group.main: Still creating... [2m50s elapsed]
module.eks-node-group.aws_eks_node_group.main: Creation complete after 2m50s [id=eks:eks-6af4d650]

Apply complete! Resources: 32 added, 0 changed, 0 destroyed.
```
